### 授权码模式
### 第一步申请授权码(浏览器请求)/oauth/authorize?client_id=c1&response_type=code&scope=all&redirect_uri=http://www.xuecheng-plus.com
### 第二步申请令牌
POST {{auth_host}}/auth/oauth/token?client_id=niuma&client_secret=niuma&grant_type=authorization_code&code=2O8Ri8&redirect_uri=http://www.xuecheng-plus.com




### 密码模式
POST {{auth_host}}/auth/oauth/token?client_id=niuma&client_secret=niuma&grant_type=password&username={"username":"admin","password":"123456","authType":"password"}

###校验jwt令牌
POST {{auth_host}}/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibml1bWFSIl0sInVzZXJfbmFtZSI6IntcImlkXCI6MixcIm5hbWVcIjpcImFkbWluMVwiLFwicm9sZVwiOjB9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY3NTc4OTI3MCwiYXV0aG9yaXRpZXMiOlsidGVhY2hlciJdLCJqdGkiOiJlMTM3YmQ5Mi1lMGIyLTRhMDktYTgyOC1hNTU3YWMyOWJhY2UiLCJjbGllbnRfaWQiOiJuaXVtYSJ9.m38R3Fp9szu6tB7y7iEMVA-v1uq21EUoHqO7MG4Z0zA

###访问资源
GET {{source_host}}/r/getR1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsibml1bWFSIl0sInVzZXJfbmFtZSI6IntcImlkXCI6MSxcIm5hbWVcIjpcImFkbWluXCIsXCJyb2xlXCI6MX0iLCJzY29wZSI6WyJhbGwiXSwiZXhwIjoxNjc1NjE5MzMzLCJhdXRob3JpdGllcyI6WyJhZG1pbiJdLCJqdGkiOiJiOTE3NTU3OS05OTJmLTQzYWQtOTNmYS0xNDA3MzVhY2RlNmEiLCJjbGllbnRfaWQiOiJuaXVtYSJ9.K1SN7I4xKcwa17VKxK5mgX221A7pbxjHrkllM6ZwQpI


